# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fa0bf88c5cc26c7f95286ffb80d89e38342a9baa6197d310240b76a637c520fc1e19458f699c8118d1f116674e730fe8713b1ea75abd50c56e5681bca14e935

test:
  secret_key_base: cb41fae037aa9ffa7e4f8fcd60d5a2eb1dbc14874ce17cefbeeab70771876f899b4960f148aa0d5e0ebe92bd379e7375ac7ab1dd6658e33d6e771e1450e27e4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
